---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/dm
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flm
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - port: 8080
    targetPort: 80
    LoadBalancer: a3eadc3c5b5574b329a118008d75d8fa-281387649.us-east-1.elb.amazonaws
