---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-app
spec:
  replicas: 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: cont-1
          image: shaikmustafa/cycle
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: flm
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
  - port: 8080
    targetPort: 80
    
